# Generated by Django 4.1.5 on 2023-04-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=500)),
                ('c_email', models.CharField(max_length=500)),
                ('c_subject', models.CharField(max_length=500)),
                ('c_message', models.CharField(max_length=500)),
            ],
        ),
    ]
